apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: wax100-blog-scaledobject
spec:
  hosts:
    - dev-blog.wax100.com
  targetPendingRequests: 10
  scaleTargetRef:
    deployment: wax100-blog
    service: wax100-blog
    port: 80
  replicas:
    min: 0
    max: 2 # Ghostはステートフル気味な運用が多いためスケールは控えめに、今回はゼロ維持主目的
