apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-wax100-blog

resources:
  - ../../base
  - db-statefulset.yaml
  - db-service.yaml
  - keda-http-scaledobject.yaml

namePrefix: dev-

patches:
  - target:
      kind: ConfigMap
      name: wax100-blog-config
    patch: |-
      - op: replace
        path: /data/url
        value: "https://dev-blog.wax100.com"
      - op: replace
        path: /data/database__connection__host
        value: "dev-wax100-blog-db"

images:
  - name: wax100-blog:latest
    newTag: dev # Dev用のタグを指定。自動更新を防ぎます。
