apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.exclusions: |
    - apiGroups:
      - "nodemanagement.gke.io"
      kinds:
      - "UpdateInfo"
      clusters:
      - "*"
