apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keda

commonAnnotations:
  config.kubernetes.io/depends-on: apps/namespaces/kyverno/Deployment/kyverno-admission-controller

helmCharts:
  - name: keda
    repo: https://kedacore.github.io/charts
    version: 2.13.0
    releaseName: keda
    namespace: keda
    valuesInline:
      nodeSelector:
        workload-type: system
