apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keda

commonAnnotations:
  config.kubernetes.io/depends-on: apps/namespaces/kyverno/Deployment/kyverno-admission-controller

helmCharts:
  - name: keda
    repo: https://kedacore.github.io/charts
    version: 2.13.0
    releaseName: keda
    namespace: keda
    valuesInline:
      nodeSelector:
        workload-type: platform
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-pool
                operator: In
                values:
                - platform-xs
                - platform-sm
                - platform-md
                - platform-lg
      tolerations:
        - key: "cloud.google.com/gke-spot"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
