apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-web-staging
  namespace: infra
spec:
  project: default
  source:
    repoURL: "https://github.com/waxsd100/k8s-platform.git"
    targetRevision: HEAD
    path: components/apps/frontend-web/overlays/staging # トラッキング対象パス (Application Workload)
  destination:
    server: "https://kubernetes.default.svc"
    namespace: stag-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
