apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-dev
  namespace: argocd
  annotations:
    # Prometheus遲峨・莉悶・addons (Sync Wave 0) 繧医ｊ繧ゅ＆繧峨↓蜑阪↓襍ｷ蜍輔＆縺帙ｋ縺溘ａ縲・1繧定ｨｭ螳・    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/waxsd100/k8s-platform.git'
    targetRevision: HEAD
    path: addons/kyverno/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Kyverno縺ｮCRD繝槭ル繝輔ぉ繧ｹ繝医し繧､繧ｺ縺悟､ｧ縺阪＞縺溘ａ蠢・・