apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  config.kubernetes.io/depends-on: apps/namespaces/external-secrets/Deployment/external-secrets

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - external-secret.yaml
  - tls-external-secret.yaml
  - service-account.yaml

configMapGenerator:
  - name: wax100-blog-config
    literals:
      - url="https://wax100.io" # 仮のURL、Overlayで上書き
      - database__client="mysql"
      - database__connection__host="wax100-db"
      - database__connection__user="ghost"
      - database__connection__database="ghost"

images:
  # ベースのイメージURL（タグ指定は各Overlayに委譲して環境ごとの更新を防ぐ）
  - name: wax100-blog:latest
    newName: asia-northeast1-docker.pkg.dev/wax100/wax100-blog-repo/ghost
