apiVersion: v1
kind: ServiceAccount
metadata:
  name: wax100-blog-sa
  annotations:
    # Workload Identity を利用して GCP サービス（Cloud SQL 等）にアクセスするための設定
    # 実際には gcloud iam service-accounts add-iam-policy-binding での紐付けも必要です
    iam.gke.io/gcp-service-account: wax100-blog-sa@wax100.iam.gserviceaccount.com
