apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
spec:
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
        - name: web
          image: nginx:alpine
          ports:
            - containerPort: 80
          # ConfigMap定義からの一括環境変数展開
          # ※機密情報は External Secrets Operator 等を用いて Secret に展開した上で参照します
          envFrom:
            - configMapRef:
                name: frontend-env-config
