apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  config.kubernetes.io/depends-on: apps/namespaces/external-secrets/Deployment/external-secrets

resources:
  - deployment.yaml
  - service.yaml
  - external-secret.yaml

configMapGenerator:
  - name: frontend-env-config
    literals:
      - APP_THEME=light
      - LOG_LEVEL=info

images:
  - name: nginx
    newName: asia-northeast1-docker.pkg.dev/wax100/docker-hub-cache/library/nginx
