apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: frontend-env-config
    literals:
      - APP_THEME=light
      - LOG_LEVEL=info

images:
  - name: nginx
    newName: asia-northeast1-docker.pkg.dev/wax100/docker-hub-cache/library/nginx
