apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Infrastructure
  - ../../components/infrastructure/nginx-ingress/base
  - ../../components/infrastructure/kubernetes-dashboard/base
  - ../../components/infrastructure/cloudflared/base

  # Addons
  - ../../addons/external-secrets/base
  - ../../addons/kyverno/overlays/staging
  # - ../../addons/prometheus/overlays/staging
  # - ../../addons/gmp/base  # GMP未有効化のためCRDが不在 (KNV1021)
  - ../../addons/keda/base
  - ../../addons/keda-http-addon/base

  # Applications
  # - ../../components/apps/frontend-web/overlays/staging # Template Application
  - ../../components/apps/wax100-blog/overlays/staging
