apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Applications
  # - ../../components/apps/frontend-web/overlays/staging # Template Application
  - ../../components/apps/wax100-blog/overlays/staging
