apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Infrastructure
  - ../../components/infrastructure/nginx-ingress/base
  - ../../components/infrastructure/kubernetes-dashboard/base
  - ../../components/infrastructure/cloudflared/base

  # Addons
  - ../../addons/external-secrets/base
  - ../../addons/kyverno/overlays/staging
  - ../../addons/prometheus/overlays/staging

  # Applications
  - ../../components/apps/frontend-web/overlays/staging
