apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-apps-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/gitops-repo.git'
    targetRevision: HEAD
    path: clusters/dev-cluster/apps # <= これが本来のApp of Appsのターゲット
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
