apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: wax100-blog-scaledobject
spec:
  hosts:
    - stag.wax100.io
  targetPendingRequests: 10
  scaleTargetRef:
    # NOTE: namePrefix: stg- が適用された後の名前を直接指定する。
    # Kustomize は CRD のカスタムフィールドを自動変換しないため、手動で合わせる必要がある。
    deployment: stg-wax100-blog
    service: stg-wax100-blog
    port: 80
  replicas:
    min: 0
    max: 1
