apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: wax100-blog-scaledobject
spec:
  hosts:
    - stg-blog.wax100.com
  targetPendingRequests: 10
  scaleTargetRef:
    deployment: wax100-blog
    service: wax100-blog
    port: 80
  replicas:
    min: 0
    max: 3
