apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-production
  namespace: infra
  annotations:
    argocd.argoproj.io/sync-wave: "0" # デプロイ順序定義: 0 (Cluster Addons)
spec:
  project: default
  source:
    repoURL: "https://github.com/waxsd100/k8s-platform.git"
    targetRevision: HEAD
    path: addons/external-secrets/base
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
