apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-production
  namespace: infra
spec:
  project: default
  source:
    repoURL: "https://github.com/waxsd100/k8s-platform.git"
    targetRevision: HEAD
    path: addons/prometheus/overlays/production
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
