apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wax100-blog
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-wax100-blog-ip
spec:
  ingressClassName: gce
  tls:
    - hosts:
        - wax100.io
      secretName: wax100-tls-secret
  rules:
    - host: wax100.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wax100-blog
                port:
                  number: 80
