apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-wax100-blog

resources:
  - ../../base
  - hpa.yaml
  - ingress.yaml
  - frontend-config.yaml
  - backend-config.yaml

namePrefix: prod-

patches:
  - path: sql-proxy-patch.yaml
  - path: scheduling-patch.yaml
  - path: gcsfuse-patch.yaml
  - patch: |
      $patch: delete
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: wax100-blog-pvc
  # GCE Ingress用: ServiceにBackendConfigアノテーションを追加
  - target:
      kind: Service
      name: wax100-blog
    patch: |-
      - op: add
        path: /metadata/annotations/cloud.google.com~1backend-config
        value: '{"default": "prod-wax100-blog-backend-config"}'
  - target:
      kind: ConfigMap
      name: wax100-blog-config
    patch: |-
      - op: replace
        path: /data/url
        value: "https://wax100.io"
      - op: replace
        path: /data/database__connection__host
        value: "127.0.0.1"
  - target:
      kind: ExternalSecret
      name: wax100-blog-external-secret
    patch: |-
      - op: replace
        path: /spec/target/name
        value: prod-wax100-blog-secret

images:
  - name: wax100-blog:latest
    # GitOps: Automated by 'promote-to-prod.yml' GitHub Action in the App Repo
    newTag: v1.0.0
