apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-wax100-blog

resources:
  - ../../base
  - hpa.yaml

namePrefix: prod-

patches:
  - path: sql-proxy-patch.yaml
  - path: scheduling-patch.yaml
  - target:
      kind: ConfigMap
      name: wax100-blog-config
    patch: |-
      - op: replace
        path: /data/url
        value: "https://blog.wax100.com"
      - op: replace
        path: /data/database__connection__host
        value: "127.0.0.1"

images:
  - name: wax100-blog:latest
    # GitOps: Automated by 'promote-to-prod.yml' GitHub Action in the App Repo
    newTag: v1.0.0
