apiVersion: apps/v1
kind: Deployment
metadata:
  name: wax100-blog
spec:
  selector:
    matchLabels:
      app: wax100-blog
  template:
    spec:
      # プロキシがGCPクレデンシャルを得るためのServiceAccount (Workload Identity等を利用想定)
      serviceAccountName: wax100-blog-sa
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.0
          args:
            - "--structured-logs"
            - "--port=3306"
            # 形式: "project-id:region:instance-name"
            - "wax100:asia-northeast1:wax100-blog-db"
            - "--private-ip" # トラブル防止のためプライベートIP接続を強制
          securityContext:
            runAsNonRoot: true
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"] # Ghost側が安全にセッションを閉じるのを待つ
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
