apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keda

helmCharts:
  - name: keda-add-ons-http
    repo: https://kedacore.github.io/charts
    version: 0.6.0
    releaseName: http-add-on
    namespace: keda
    valuesInline:
      nodeSelector:
        workload-type: platform
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-pool
                operator: In
                values:
                - platform-xs
                - platform-sm
                - platform-md
                - platform-lg
      tolerations:
        - key: "cloud.google.com/gke-spot"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
