apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keda

helmCharts:
  - name: keda-add-ons-http
    repo: https://kedacore.github.io/charts
    version: 0.6.0
    releaseName: http-add-on
    namespace: keda
