apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keda

helmCharts:
  - name: keda-add-ons-http
    repo: https://kedacore.github.io/charts
    version: 0.6.0
    releaseName: http-add-on
    namespace: keda
    valuesInline:
      images:
        kubeRbacProxy:
          name: quay.io/brancz/kube-rbac-proxy
          tag: v0.13.0
      operator:
        nodeSelector: &platform-node-selector
          workload-type: platform
        affinity: &platform-affinity
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: node-pool
                      operator: In
                      values:
                        - platform-xs
              - weight: 80
                preference:
                  matchExpressions:
                    - key: node-pool
                      operator: In
                      values:
                        - platform-sm
              - weight: 40
                preference:
                  matchExpressions:
                    - key: node-pool
                      operator: In
                      values:
                        - platform-md
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-pool
                  operator: In
                  values:
                  - platform-xs
                  - platform-sm
                  - platform-md
                  - platform-lg
        tolerations: &platform-tolerations
          - key: "cloud.google.com/gke-spot"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
      scaler:
        nodeSelector: *platform-node-selector
        affinity: *platform-affinity
        tolerations: *platform-tolerations
      interceptor:
        nodeSelector: *platform-node-selector
        affinity: *platform-affinity
        tolerations: *platform-tolerations
