apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-frontend

resources:
  - ../../base
  - hpa.yaml

namePrefix: prod-

images:
  - name: nginx
    newTag: "1.25.0-alpine"

patches:
  - path: toleration-patch.yaml
