apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-frontend

resources:
  - ../../base

namePrefix: prod-

images:
  - name: nginx
    newTag: "1.25.0-alpine"

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: frontend-web
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 4
      - op: replace
        path: /spec/maxReplicas
        value: 10
  - path: toleration-patch.yaml
