apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-frontend

resources:
  - ../../base

namePrefix: prod-

images:
  - name: nginx
    newTag: "1.25.0-alpine"

replicas:
  - name: frontend-web
    count: 5

patches:
  - path: toleration-patch.yaml
