apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterpolicy-registry-mirror.yaml
  - clusterpolicy-config-sync.yaml

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    releaseName: kyverno
    namespace: kyverno
    version: 3.2.0
    includeCRDs: true
    valuesInline:
      admissionController:
        nodeSelector:
          workload-type: system
      backgroundController:
        nodeSelector:
          workload-type: system
      cleanupController:
        nodeSelector:
          workload-type: system
        image:
          # Use a more reliable image source for cleanup jobs
          repository: public.ecr.aws/bitnami/kubectl
          tag: 1.29.2
      reportsController:
        nodeSelector:
          workload-type: system

images:
  - name: ghcr.io/kyverno/kyverno
    newName: asia-northeast1-docker.pkg.dev/wax100/ghcr-cache/kyverno/kyverno
  - name: ghcr.io/kyverno/kyvernopre
    newName: asia-northeast1-docker.pkg.dev/wax100/ghcr-cache/kyverno/kyvernopre
  - name: ghcr.io/kyverno/cleanup-controller
    newName: asia-northeast1-docker.pkg.dev/wax100/ghcr-cache/kyverno/cleanup-controller
  - name: ghcr.io/kyverno/reports-controller
    newName: asia-northeast1-docker.pkg.dev/wax100/ghcr-cache/kyverno/reports-controller
  - name: ghcr.io/kyverno/background-controller
    newName: asia-northeast1-docker.pkg.dev/wax100/ghcr-cache/kyverno/background-controller
