apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - clusterpolicy-registry-mirror.yaml
  - clusterpolicy-app-scheduling.yaml
  - clusterpolicy-app-hardening.yaml
  - clusterpolicy-build-scheduling.yaml
  - clusterpolicy-canine-boundary.yaml
  - clusterpolicy-config-sync-placement.yaml
  - deletingpolicy-config-sync-placement.yaml
  - clusterpolicy-db-backup-exec.yaml
  - clusterpolicy-pvc-backup-job.yaml
  - clusterpolicy-headlamp-edit.yaml
  - clusterpolicy-headlamp-backup-ops.yaml
  - clusterpolicy-environment-isolation.yaml
  - clusterpolicy-environment-access.yaml
  - clusterpolicy-ingress-hosts.yaml

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    releaseName: kyverno
    namespace: kyverno
    version: 3.9.1
    includeCRDs: true
    skipTests: true
    valuesInline:
      admissionController:
        # 1 本だとローリング更新のたびにアプリ Pod を作れない時間ができる
        replicas: 2
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        nodeSelector:
          workload-type: platform
        tolerations:
          - key: "cloud.google.com/gke-spot"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
      backgroundController:
        nodeSelector:
          workload-type: platform
        tolerations:
          - key: "cloud.google.com/gke-spot"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
      cleanupController:
        nodeSelector:
          workload-type: platform
        tolerations:
          - key: "cloud.google.com/gke-spot"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
      reportsController:
        nodeSelector:
          workload-type: platform
        tolerations:
          - key: "cloud.google.com/gke-spot"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"

images:
  - name: ghcr.io/kyverno/kyverno
    newName: asia-northeast1-docker.pkg.dev/wax100/ghcr-cache/kyverno/kyverno
  - name: ghcr.io/kyverno/kyvernopre
    newName: asia-northeast1-docker.pkg.dev/wax100/ghcr-cache/kyverno/kyvernopre
  - name: ghcr.io/kyverno/cleanup-controller
    newName: asia-northeast1-docker.pkg.dev/wax100/ghcr-cache/kyverno/cleanup-controller
  - name: ghcr.io/kyverno/reports-controller
    newName: asia-northeast1-docker.pkg.dev/wax100/ghcr-cache/kyverno/reports-controller
  - name: ghcr.io/kyverno/background-controller
    newName: asia-northeast1-docker.pkg.dev/wax100/ghcr-cache/kyverno/background-controller
