kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: frontend-web
spec:
  # The host expected in the HTTP request. Must match Ingress/Service routing.
  # Can be multiple, e.g., ["dev.example.com", "frontend-web"]
  hosts: 
    - frontend-web
    - frontend-web.development.svc.cluster.local
  scaleTargetRef:
    deployment: frontend-web
    service: frontend-web
    port: 80
  replicas:
    min: 0
    max: 2
