apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-frontend

resources:
  - ../../base
  - pdb.yaml

namePrefix: dev-

images:
  - name: nginx
    newTag: "1.25.0-alpine"

patches:
  - path: spot-patch.yaml
  - path: toleration-patch.yaml
