# PodDisruptionBudget: Spot Preemptionやノードドレイン時の最低稼働Pod数を保証
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-web-pdb
spec:
  # 中断発生時でも最低1台のPodが稼働し続けることを強制する
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend-web
