apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
spec:
  template:
    spec:
      tolerations:
        - key: environment
          operator: Equal
          value: development
          effect: NoSchedule
