apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/gitops-repo.git'
    targetRevision: HEAD
    path: components/infrastructure/argocd/overlays/dev # dev環境のパッチを当てたArgoCD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
