apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development-infrastructure-root
  namespace: infra
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: "https://github.com/waxsd100/k8s-platform.git"
    targetRevision: HEAD
    path: clusters/development-cluster/infrastructure
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
