apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: oci
  oci:
    image: asia-northeast1-docker.pkg.dev/wax100/config-sync-repo/manifests:main
    dir: clusters/development-cluster
    auth: gcpserviceaccount
    gcpServiceAccountEmail: config-sync-sa@wax100.iam.gserviceaccount.com
  override:
    resources:
      - containerName: "reconciler"
        cpuRequest: "50m"
        memoryRequest: "128Mi"
      - containerName: "oci-sync"
        cpuRequest: "10m"
        memoryRequest: "64Mi"
