apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

# アップストリーム（公式配布版）リソースの参照
resources:
  - github.com/prometheus-operator/kube-prometheus//manifests/setup?ref=main
  - github.com/prometheus-operator/kube-prometheus//manifests?ref=main

images:
  - name: registry.k8s.io/kube-state-metrics/kube-state-metrics
    newName: asia-northeast1-docker.pkg.dev/wax100/k8s-cache/kube-state-metrics/kube-state-metrics
  - name: quay.io/prometheus/prometheus
    newName: asia-northeast1-docker.pkg.dev/wax100/quay-cache/prometheus/prometheus
  - name: quay.io/prometheus/alertmanager
    newName: asia-northeast1-docker.pkg.dev/wax100/quay-cache/prometheus/alertmanager
