kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: frontend-web
spec:
  hosts:
    - frontend-web
    - frontend-web.staging.svc.cluster.local
  scaleTargetRef:
    name: frontend-web
    kind: Deployment
    apiVersion: apps/v1
    service: frontend-web
    port: 80
  replicas:
    min: 0
    max: 2
