apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stag-frontend

resources:
  - ../../base
  - pdb.yaml

namePrefix: stag-

images:
  - name: nginx
    newTag: "1.25.0-alpine"

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: frontend-web
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 5
  - path: spot-patch.yaml
  - path: toleration-patch.yaml
