apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-infrastructure-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/waxsd100/k8s-platform.git'
    targetRevision: HEAD
    path: clusters/production-cluster/infrastructure
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
