apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: oci
  oci:
    image: asia-northeast1-docker.pkg.dev/wax100/config-sync-repo/manifests:main
    dir: clusters/production-cluster
    auth: gcpserviceaccount
    gcpServiceAccountEmail: config-sync-sa@wax100.iam.gserviceaccount.com
  overrides:
    components:
      - name: otel-collector
        containerName: otel-collector
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
        tolerations:
          - operator: Exists
